//Challenge:
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.



let listaFibonacci =[0, 1];

function creaSecuenciaFibonacci() {

  for(let i = 2, r ; r = listaFibonacci[i - 2] + listaFibonacci[i - 1], r < 4000000  ; i++) {
      
    listaFibonacci.push(listaFibonacci[i - 2] + listaFibonacci[i - 1]);    
  };

  console.log("Secuencia Fibonacci hasta 4.000.000: " + listaFibonacci); 

  return listaFibonacci; 
};
  

  
function chequeaSiEsPar() {
        
  let listaFiboPares=[];

  let longitudListaFibonacci = listaFibonacci.length;

  for (i = 0 ; i < longitudListaFibonacci ; i++) {
          
    let numeroPar = listaFibonacci[i] % 2;

    if (numeroPar === 0) {

      listaFiboPares.push(listaFibonacci[i])
        };
  }

  console.log("Numero pares de la Secuencia Fibonacci hasta 4.000.000: " + listaFiboPares);

  const resultado = (x, y) => x + y; 

  console.log("Suma de numeros Fibonacci pares del 1 a 4.000.000: " + listaFiboPares.reduce(resultado));
    
}

function resuelveChallenge() {
  creaSecuenciaFibonacci();
  chequeaSiEsPar();
}

resuelveChallenge();  //Output: 4613732
